name: CopyKit
options:
  bundleIdPrefix: com.hsbc
  
  
targets:

  CopyKit:
    type: tool
    sources: CopyKit
    platform: macOS
    dependencies:
      - framework: Commandant.framework

  HKSampleApp:
    type: application
    sources:
      - SampleApp
      - CopyKit/Core/CopyBundleCovertible.swift
    platform: iOS
    deploymentTarget: "13.0"
    settings: 
      "AREA_CODE": "HK"


  UKSampleApp:
    type: application
    sources:
      - SampleApp
      - CopyKit/Core/CopyBundleCovertible.swift
    platform: iOS
    deploymentTarget: "13.0"
    settings: 
      "AREA_CODE": "UK"


  ConvertCommand:
    type: tool
    platform: macOS
    sources: Empty
    postBuildScripts:
      - path: preBuildSheel/covertCopy.sh
        name: covertCopy



    
    
